In [1]:
import os 
import numpy as np

# Basic Numpay Arrays

In [4]:
n = np.array([1, 2, 3, 4])

In [3]:
l = [1, 2, 3, 4]

In [6]:
print(n.dtype)
print(l[1].dtype)

int32


AttributeError: 'int' object has no attribute 'dtype'

In [7]:
n[1]

2

In [8]:
n[:2]

array([1, 2])

In [10]:
n[[1, 2, 3]]       # note how it's an array passed here [1, 2, 3] not (1, 2, 3), which is a tuple

array([2, 3, 4])

# Dimensions and shapes

In [12]:
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

In [13]:
A.shape

(2, 3)

# Indexing and slicing matrices

In [23]:
B = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [16]:
B[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [27]:
B[1] = [11, 12, 13]
B

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 7,  8,  9]])

# Summary Statistics

In [28]:
B.sum()

66

In [29]:
B.sum(axis = 0)

array([19, 22, 25])

In [30]:
B[:,0].sum(axis = 0)

19

In [33]:
b = B[1, :].sum()

In [34]:
b

36

In [35]:
B.mean()

7.333333333333333

In [36]:
B.mean(axis = 1)

array([ 2., 12.,  8.])

#Broadcasting and vectorized operations


In [37]:
a= np.arange(4) # Numpy vectorization: a method of performing array operations without the use for loops

In [38]:
a

array([0, 1, 2, 3])

In [51]:
c = np.random.randint(100, size = (3,3))
c

array([[ 4, 66, 79],
       [27,  5, 27],
       [59, 52, 24]])

In [40]:
b = a + 10 # this is actually a very powerful method, and super fast, if you want to apply one calculation to every element in an array.

In [41]:
b

array([10, 11, 12, 13])

In [42]:
a # notice how a didn't change instead, a + 10 created a new array b

array([0, 1, 2, 3])

In [43]:
a +=100
a # notice how in this case, a is modified

array([100, 101, 102, 103])

#boolean arrays


In [44]:
a = np.arange(4)


In [45]:
a

array([0, 1, 2, 3])

In [47]:
a[a>=2]

array([2, 3])

In [48]:
a >= 2  # notice this returns an array of boolean array

array([False, False,  True,  True])

In [49]:
a >= a.mean() # this is a boolean array. 

array([False, False,  True,  True])

In [50]:
a[a>=a.mean()]

array([2, 3])

In [ ]:
# boolean arrays can be used to filter, this is important. 

#linear algebra


In [52]:
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

B = np.array(
    [
        [6,5],
        [4,3],
        [2,1]
    ]
)

In [53]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [54]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [55]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [56]:
A # Note that A didn't change value.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

# Sizes of objects in memory


In [59]:
import sys

In [61]:
# an interger in Python is >24bytaes
sys.getsizeof(1)

28

In [62]:
# Long are even larger
sys.getsizeof(10**100)

72

In [63]:
# Numpy is much smaller
np.dtype(int).itemsize

4

In [64]:
np.dtype(float).itemsize

8

In [66]:
# compare the list calculations between python list and numpy array 
l = list(range(1000))
a = np.arange(1000)

In [68]:
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 2 ms


332833500

In [67]:
%time sum(x**2 for x in l)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

# Useful Numpy functions

In [69]:
# random: generates a random float number between 0 and 1
np.random.random(size = 2)

array([0.37335714, 0.75022008])

In [70]:
np.random.normal(size = 2) # gerneate random numbers from a normal dis with a specific mean and standard deviation

array([ 0.70488794, -0.77346822])

In [71]:
np.random.rand(2,4) # genreate random numbers in a given shape from a uniform distribution [0,1)

array([[0.90405261, 0.13732683, 0.30322169, 0.9127215 ],
       [0.35921696, 0.05912874, 0.03655121, 0.0729303 ]])

In [72]:
# arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [74]:
np.arange(0,1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [75]:
# Reshpae
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
#linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [80]:
np.linspace(0,1,20).reshape(2,10)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [79]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [81]:
# zero, ones, empty
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [82]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [85]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [86]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [87]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [88]:
# Identity and eye
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])